"""Builds Int_StplGITPricing.sql - the whole database in one script - from the
numbered files in this folder. Edit those files, then run: python build_single_script.py"""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = [
    '00_CreateDatabase.sql',
    '01_Core/01_Schema_And_Tables.sql',
    '02_IntlGit/01_Schema_And_Tables.sql',
    '02_IntlGit/02_Types_Function_View.sql',
    '01_Core/02_Procedures.sql',
    '02_IntlGit/03_Procedures.sql',
    '03_Security.sql',
    '04_MasterData.sql',
    '05_TourData.sql',
]
HEAD = '''/*
    Int_StplGITPricing.sql
    ---------------------------------------------------------------------------
    The complete database Int_StplGITPricing in ONE script. It references no
    other database, linked server or synonym.

      1. database Int_StplGITPricing (if missing)
      2. schema core    : users, notifications, email log
         schema intlgit : International GIT pricing - 36 tables in total,
                          10 table types, fn_PriceMatrix, vw_ChangeSetProgress
      3. 67 stored procedures
      4. role stpl_pricing_app (EXECUTE on core and intlgit)
      5. master data: fare bands, occupancies, 12 hubs, 3 starter accounts
      6. tour data: 23 tours, 266 tour-hubs, their departure dates, airfares
         and flight routings

    Open in SSMS connected to the server (any database) and press F5.
    Safe to run again: tables only if missing, procedures CREATE OR ALTER,
    master data only if missing, tours only if there are none yet.

    GENERATED by build_single_script.py from the numbered files - edit those.
*/
'''
out = [HEAD]
for i, p in enumerate(PARTS):
    text = open(os.path.join(HERE, p), encoding='utf-8-sig').read().rstrip() + '\n'
    out.append('\n-- ' + '=' * 77 + '\n-- ' + p + '\n-- ' + '=' * 77 + '\n')
    out.append(text)
    if i == 0:
        out.append('USE Int_StplGITPricing;\nGO\n')
open(os.path.join(HERE, 'Int_StplGITPricing.sql'), 'w', encoding='utf-8-sig').write(''.join(out))
print('Int_StplGITPricing.sql written')
